dist: xenial
sudo: false
latex: true
language: r
r: release

warnings_are_errors: false

cache:
  packages: true
  
apt_packages:
  - libgdal-dev
  - libudunits2-dev

r_packages:
  - rsconnect
  - shiny
  - shinydashboard
  - DT
  - reshape
  - funModeling
  - GGally
  - dplyr
  - datasets
  - ggplot2
  - e1071
  - randomForest
  - tree
  - caret
  - parallelSVM
  - gbm
  - ggvis
  
script:
  - R -f deploy.R
